name: performance

on: [pull_request]

jobs:
  compressed-size:
    name: compressed-size
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: necolas/compressed-size-action@master
      with:
        build-script: "build"
        pattern: "./packages/stylex/lib/{stylex.js,StyleXSheet.js}"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
